name: CI/CD DevOps Hola Mundo

on:
  push:
    branches:
      - main  # Se ejecutará al hacer push a main

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    steps:
      # 1. Descargar código
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Iniciar sesión en Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Construir imagen Docker
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/hola-mundo-app:latest .

      # 4. Subir imagen a Docker Hub
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/hola-mundo-app:latest

  deploy-to-render:
    needs: build-and-push-docker
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Render
        run: |
          curl -X POST "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys" \
          -H "Accept: application/json" \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"
